### ISSUE TITLE
Passing multiple glob patterns to soyDeps can easily result in duplicated templates

### ISSUE THREAD

**Issue by robframpton** [metal/metal-tools-soy#9]
When passing multiple glob patterns to `soyDeps`, if two glob patterns match the same file, the file will be included twice in the soy compilation and result in an error.

```bash
Template 'Component.render' already defined at metal-some-component/src/Component.soy
```
Obviously this was easy to fix by changing my glob patterns, but it would be nice if we deduped files so they don't get included twice. I think part of the issues is that one of my patterns was a resolved absolute file path to a specific dependency, while the other was just a relative file path to `node_modules`.

**Comment by fernandosouza** [comment]
Could it be the same error I'm facing during the refactoring of [Quartz test infrastructure](https://github.com/metal/metal-quartz-components/issues/16)?

```javascript
Uncaught Error: Namespace "goog.string" already declared.  at bundle.js:7683
```

**Comment by jbalsas** [comment]
Yeah, I think I've seen this as well... might be nice to fix it :)

**Comment by julien** [comment]
Hi,

I'm also facing the same issue and wanted to share.

In my case, the `soyDeps` are redeclaring the same templates as the `src` files although they have a different path, due to a configuration issue on my side.

My first idea was to check if the file paths for `soyDeps` already exist in `args` before [adding](https://github.com/metal/metal-tools-soy/blob/master/lib/pipelines/compileSoy.js#L62) them.

But, now I'm not sure if that's a better solution, because two files might have a different path but have the same content. What do you think?

**Comment by jbalsas** [comment]
This is now definitely doable now that we have our own [soy parser](https://github.com/metal/soyparser). We can parse the dependencies and dedupe them based on their `namespace`.
